# Generated by Django 3.2.7 on 2021-11-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMSapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('reqId', models.AutoField(primary_key=True, serialize=False)),
                ('userClkIn', models.CharField(default='-', max_length=50)),
                ('userID', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(default='Not yet', max_length=50)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Request',
            },
        ),
        migrations.CreateModel(
            name='Timings',
            fields=[
                ('timeId', models.AutoField(primary_key=True, serialize=False)),
                ('usrId', models.IntegerField()),
                ('date', models.CharField(default='-', max_length=50)),
                ('userClkIn', models.CharField(default='-', max_length=50)),
                ('userClkOut', models.CharField(default='-', max_length=50)),
                ('userBrkIn', models.CharField(default='-', max_length=50)),
                ('userBrkOut', models.CharField(default='-', max_length=50)),
                ('status', models.CharField(default='-', max_length=50)),
                ('hasHalfDayAppointed', models.BooleanField(default=False)),
                ('hasLeaveAppointed', models.BooleanField(default=False)),
                ('overtime', models.BooleanField(default=False)),
                ('numOfHours', models.CharField(default=0, max_length=50)),
            ],
            options={
                'db_table': 'Timing',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
