# Generated by Django 3.2.9 on 2021-11-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMSapp', '0002_auto_20211102_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('userClkIn', models.CharField(max_length=50)),
                ('userClkOut', models.CharField(max_length=20)),
                ('userBrkIn', models.CharField(max_length=20)),
                ('userBrkOut', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Timings',
            },
        ),
    ]
