# Generated by Django 3.2.7 on 2021-11-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMSapp', '0002_auto_20211109_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('logId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(default='-', max_length=50)),
                ('userId', models.IntegerField()),
                ('hasLoggedIn', models.BooleanField(default=False)),
                ('hasClockedIn', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Log',
            },
        ),
    ]
