# Generated by Django 3.2.7 on 2021-11-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMSapp', '0003_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='hasClockedIn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='hasLoggedIn',
            field=models.BooleanField(default=False),
        ),
    ]
