# Generated by Django 3.2.7 on 2021-11-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMSapp', '0008_auto_20211103_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='timings',
            name='status',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='timings',
            name='userBrkIn',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='timings',
            name='userBrkOut',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='timings',
            name='userClkIn',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='timings',
            name='userClkOut',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
