# Generated by Django 3.2.7 on 2021-11-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMSapp', '0010_timings_hashalfdayappointed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('reqId', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Request',
            },
        ),
    ]
