# Generated by Django 3.2.7 on 2021-11-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMSapp', '0011_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default='Not yet', max_length=50),
        ),
    ]
