# Generated by Django 3.2.9 on 2021-11-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMSapp', '0013_request_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='timings',
            name='hasLeaveAppointed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timings',
            name='numOfHours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timings',
            name='overtime',
            field=models.BooleanField(default=False),
        ),
    ]
