# Generated by Django 3.2.9 on 2021-11-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMSapp', '0014_auto_20211105_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timings',
            name='numOfHours',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
