# Generated by Django 3.2.9 on 2021-11-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMSapp', '0016_request_userclkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='timings',
            name='date',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
